### ISSUE TITLE
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by ericquan99** [RussellTsuchida/snefy#1]
integrate.py line 292, in `_evaluate_kernel`

`if not (extra_input == 0):`

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

**Comment by RussellTsuchida** [comment]
Thanks very much for your interest in our work! Could you help me to reproduce the error on my end? Which code are you running?
